users:
- id: U10000
  name: J.R.R Hemingway
  username: fakeuser
  password: fakepass
  country: CAD
  address1: 555 La Floridita Way
  phone: 15551234567


endpoints:
- id: jshdjkahkj
  name: endpoint1

- id: hsdjkhakjdh
  name: endpoint2
